# Generated by Django 3.2.9 on 2021-11-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20211108_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
